# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_manage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(927, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.Download_List = QtWidgets.QListView(Form)
        self.Download_List.setGeometry(QtCore.QRect(10, 90, 911, 461))
        self.Download_List.setStyleSheet("background:rgba(0,0,0,50);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Download_List.setObjectName("Download_List")
        self.Setting_Button = QtWidgets.QPushButton(Form)
        self.Setting_Button.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.Setting_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Setting_Button.setObjectName("Setting_Button")
        self.Download_Manage_Button = QtWidgets.QPushButton(Form)
        self.Download_Manage_Button.setGeometry(QtCore.QRect(170, 20, 131, 41))
        self.Download_Manage_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Download_Manage_Button.setObjectName("Download_Manage_Button")
        self.Sgin_out_Button = QtWidgets.QPushButton(Form)
        self.Sgin_out_Button.setGeometry(QtCore.QRect(610, 20, 131, 41))
        self.Sgin_out_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_out_Button.setObjectName("Sgin_out_Button")
        self.Background = QtWidgets.QLabel(Form)
        self.Background.setGeometry(QtCore.QRect(0, 0, 931, 571))
        self.Background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap(":/jpg/background.jpg"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.Login_Username = QtWidgets.QLabel(Form)
        self.Login_Username.setGeometry(QtCore.QRect(760, 20, 131, 41))
        self.Login_Username.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Login_Username.setObjectName("Login_Username")
        self.Sgin_in_Button = QtWidgets.QPushButton(Form)
        self.Sgin_in_Button.setGeometry(QtCore.QRect(460, 20, 131, 41))
        self.Sgin_in_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_in_Button.setObjectName("Sgin_in_Button")
        self.Main_Button = QtWidgets.QPushButton(Form)
        self.Main_Button.setGeometry(QtCore.QRect(30, 20, 131, 41))
        self.Main_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Main_Button.setObjectName("Main_Button")
        self.Background.raise_()
        self.Main_Button.raise_()
        self.Sgin_in_Button.raise_()
        self.Download_Manage_Button.raise_()
        self.Setting_Button.raise_()
        self.Sgin_out_Button.raise_()
        self.Login_Username.raise_()
        self.Download_List.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "哔哩哔哩视频下载器 Beta v0.1 作者：菠萝小西瓜  φ(゜▽゜*)♪"))
        self.Setting_Button.setText(_translate("Form", "设置"))
        self.Download_Manage_Button.setText(_translate("Form", "下载管理"))
        self.Sgin_out_Button.setText(_translate("Form", "退出B站账号"))
        self.Login_Username.setText(_translate("Form", "TextLabel"))
        self.Sgin_in_Button.setText(_translate("Form", "登录B站账号"))
        self.Main_Button.setText(_translate("Form", "首页"))
import image_rc
