# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(929, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.Background = QtWidgets.QLabel(Form)
        self.Background.setGeometry(QtCore.QRect(0, 0, 931, 571))
        self.Background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap(":/jpg/background.jpg"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.Login_Background = QtWidgets.QLabel(Form)
        self.Login_Background.setGeometry(QtCore.QRect(10, 80, 911, 471))
        self.Login_Background.setStyleSheet("background:rgba(0,0,0,60);")
        self.Login_Background.setText("")
        self.Login_Background.setObjectName("Login_Background")
        self.Username_Tips = QtWidgets.QLabel(Form)
        self.Username_Tips.setGeometry(QtCore.QRect(50, 180, 51, 21))
        self.Username_Tips.setStyleSheet("background:rgba(0,0,0,0);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Username_Tips.setObjectName("Username_Tips")
        self.Password_Tips = QtWidgets.QLabel(Form)
        self.Password_Tips.setGeometry(QtCore.QRect(60, 240, 31, 16))
        self.Password_Tips.setStyleSheet("background:rgba(0,0,0,0);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Password_Tips.setObjectName("Password_Tips")
        self.Login_in_Button_1 = QtWidgets.QPushButton(Form)
        self.Login_in_Button_1.setGeometry(QtCore.QRect(410, 290, 121, 41))
        self.Login_in_Button_1.setStyleSheet("background:rgba(0,0,0,80);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Login_in_Button_1.setObjectName("Login_in_Button_1")
        self.Sgin_in_Ways = QtWidgets.QGroupBox(Form)
        self.Sgin_in_Ways.setGeometry(QtCore.QRect(640, 130, 241, 211))
        self.Sgin_in_Ways.setStyleSheet("background:rgba(0,0,0,0);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_in_Ways.setObjectName("Sgin_in_Ways")
        self.Bilibili = QtWidgets.QRadioButton(self.Sgin_in_Ways)
        self.Bilibili.setGeometry(QtCore.QRect(20, 40, 181, 16))
        self.Bilibili.setObjectName("Bilibili")
        self.BiliAPI = QtWidgets.QRadioButton(self.Sgin_in_Ways)
        self.BiliAPI.setGeometry(QtCore.QRect(20, 100, 211, 16))
        self.BiliAPI.setObjectName("BiliAPI")
        self.Biliplus = QtWidgets.QRadioButton(self.Sgin_in_Ways)
        self.Biliplus.setGeometry(QtCore.QRect(20, 160, 151, 16))
        self.Biliplus.setObjectName("Biliplus")
        self.Biliplus_login_Tips = QtWidgets.QLabel(Form)
        self.Biliplus_login_Tips.setGeometry(QtCore.QRect(60, 380, 301, 21))
        self.Biliplus_login_Tips.setStyleSheet("background:rgba(0,0,0,0);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Biliplus_login_Tips.setObjectName("Biliplus_login_Tips")
        self.Login_in_Button_2 = QtWidgets.QPushButton(Form)
        self.Login_in_Button_2.setGeometry(QtCore.QRect(560, 420, 121, 41))
        self.Login_in_Button_2.setStyleSheet("background:rgba(0,0,0,110);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Login_in_Button_2.setObjectName("Login_in_Button_2")
        self.Setting_Button = QtWidgets.QPushButton(Form)
        self.Setting_Button.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.Setting_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Setting_Button.setObjectName("Setting_Button")
        self.Download_Manage_Button = QtWidgets.QPushButton(Form)
        self.Download_Manage_Button.setGeometry(QtCore.QRect(170, 20, 131, 41))
        self.Download_Manage_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Download_Manage_Button.setObjectName("Download_Manage_Button")
        self.Sgin_out_Button = QtWidgets.QPushButton(Form)
        self.Sgin_out_Button.setGeometry(QtCore.QRect(610, 20, 131, 41))
        self.Sgin_out_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_out_Button.setObjectName("Sgin_out_Button")
        self.Login_Username = QtWidgets.QLabel(Form)
        self.Login_Username.setGeometry(QtCore.QRect(760, 20, 131, 41))
        self.Login_Username.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Login_Username.setObjectName("Login_Username")
        self.Sgin_in_Button = QtWidgets.QPushButton(Form)
        self.Sgin_in_Button.setGeometry(QtCore.QRect(460, 20, 131, 41))
        self.Sgin_in_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_in_Button.setObjectName("Sgin_in_Button")
        self.Main_Button = QtWidgets.QPushButton(Form)
        self.Main_Button.setGeometry(QtCore.QRect(30, 20, 131, 41))
        self.Main_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Main_Button.setObjectName("Main_Button")
        self.Username_Edit = QtWidgets.QLineEdit(Form)
        self.Username_Edit.setGeometry(QtCore.QRect(110, 170, 421, 41))
        self.Username_Edit.setStyleSheet("background:rgba(0,0,0,70);border:none;color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:18px")
        self.Username_Edit.setObjectName("Username_Edit")
        self.Password_Edit = QtWidgets.QLineEdit(Form)
        self.Password_Edit.setGeometry(QtCore.QRect(110, 230, 421, 41))
        self.Password_Edit.setStyleSheet("background:rgba(0,0,0,70);border:none;color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:18px")
        self.Password_Edit.setObjectName("Password_Edit")
        self.Biliplus_Edit = QtWidgets.QLineEdit(Form)
        self.Biliplus_Edit.setGeometry(QtCore.QRect(50, 420, 491, 41))
        self.Biliplus_Edit.setStyleSheet("background:rgba(0,0,0,110);border:none;color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:18px\n"
"")
        self.Biliplus_Edit.setObjectName("Biliplus_Edit")
        self.Background.raise_()
        self.Login_Background.raise_()
        self.Username_Tips.raise_()
        self.Password_Tips.raise_()
        self.Login_in_Button_1.raise_()
        self.Sgin_in_Ways.raise_()
        self.Biliplus_login_Tips.raise_()
        self.Login_in_Button_2.raise_()
        self.Login_Username.raise_()
        self.Sgin_in_Button.raise_()
        self.Sgin_out_Button.raise_()
        self.Download_Manage_Button.raise_()
        self.Setting_Button.raise_()
        self.Main_Button.raise_()
        self.Username_Edit.raise_()
        self.Password_Edit.raise_()
        self.Biliplus_Edit.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "哔哩哔哩视频下载器 Beta v0.1 作者：菠萝小西瓜  φ(゜▽゜*)♪"))
        self.Username_Tips.setText(_translate("Form", "账户名"))
        self.Password_Tips.setText(_translate("Form", "密码"))
        self.Login_in_Button_1.setText(_translate("Form", "登录"))
        self.Sgin_in_Ways.setTitle(_translate("Form", "登录方式"))
        self.Bilibili.setText(_translate("Form", "B站官方登录（维护中）"))
        self.BiliAPI.setText(_translate("Form", "KAAAsS BiliAPI 第三方登录"))
        self.Biliplus.setText(_translate("Form", "BiliPlus 第三方登录"))
        self.Biliplus_login_Tips.setText(_translate("Form", "MCBBS授权链接（BiliPlus 第三方登录专用）"))
        self.Login_in_Button_2.setText(_translate("Form", "登录"))
        self.Setting_Button.setText(_translate("Form", "设置"))
        self.Download_Manage_Button.setText(_translate("Form", "下载管理"))
        self.Sgin_out_Button.setText(_translate("Form", "退出B站账号"))
        self.Login_Username.setText(_translate("Form", "TextLabel"))
        self.Sgin_in_Button.setText(_translate("Form", "登录B站账号"))
        self.Main_Button.setText(_translate("Form", "首页"))
        self.Username_Edit.setPlaceholderText(_translate("Form", "手机号码/邮箱账号/账号名"))
import image_rc
