# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ui_download_manage
import ui_login
import ui_setting


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background:rgba(0,0,0,30);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 931, 571))
        self.Background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap(":/jpg/background.jpg"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.Tips = QtWidgets.QLabel(self.centralwidget)
        self.Tips.setGeometry(QtCore.QRect(30, 260, 331, 31))
        self.Tips.setStyleSheet("background:rgba(0,0,0,0);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:18px")
        self.Tips.setObjectName("Tips")
        self.Main_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Main_Button.setGeometry(QtCore.QRect(30, 20, 131, 41))
        self.Main_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Main_Button.setObjectName("Main_Button")
        self.Download_Manage_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Download_Manage_Button.setGeometry(QtCore.QRect(170, 20, 131, 41))
        self.Download_Manage_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Download_Manage_Button.setObjectName("Download_Manage_Button")
        self.Setting_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Setting_Button.setGeometry(QtCore.QRect(310, 20, 131, 41))
        self.Setting_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Setting_Button.setObjectName("Setting_Button")
        self.Sgin_in_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Sgin_in_Button.setGeometry(QtCore.QRect(460, 20, 131, 41))
        self.Sgin_in_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_in_Button.setObjectName("Sgin_in_Button")
        self.Sgin_out_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Sgin_out_Button.setGeometry(QtCore.QRect(610, 20, 131, 41))
        self.Sgin_out_Button.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Sgin_out_Button.setObjectName("Sgin_out_Button")
        self.Login_Username = QtWidgets.QLabel(self.centralwidget)
        self.Login_Username.setGeometry(QtCore.QRect(760, 20, 131, 41))
        self.Login_Username.setStyleSheet("background:rgba(0,0,0,30);color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:15px")
        self.Login_Username.setObjectName("Login_Username")
        self.Search_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Search_Edit.setGeometry(QtCore.QRect(30, 210, 871, 41))
        self.Search_Edit.setStyleSheet("background:rgba(0,0,0,50);border:none;color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:18px")
        self.Search_Edit.setObjectName("Search_Edit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "哔哩哔哩视频下载器 Beta v0.1 作者：菠萝小西瓜  φ(゜▽゜*)♪"))
        self.Tips.setText(_translate("MainWindow", "Tips：目前只支持番剧、视频哟( •̀ ω •́ )✧"))
        self.Main_Button.setText(_translate("MainWindow", "首页"))
        self.Download_Manage_Button.setText(_translate("MainWindow", "下载管理"))
        self.Setting_Button.setText(_translate("MainWindow", "设置"))
        self.Sgin_in_Button.setText(_translate("MainWindow", "登录B站账号"))
        self.Sgin_out_Button.setText(_translate("MainWindow", "退出B站账号"))
        self.Login_Username.setText(_translate("MainWindow", "TextLabel"))
        self.Search_Edit.setPlaceholderText(_translate("MainWindow", "请在此输入B站AV/BV号或视频地址..然后按回车.."))

import image_rc